name: CI | Nightly

defaults:
  run:
    shell: bash

env:
  CI: true

on:
  schedule:
    # Run at midnight every working day
    - cron: '0 0 * * Mon-Fri'
  workflow_dispatch:

jobs:

  ci-nightly:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:

      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          ref: develop

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup node cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install
        run: npm ci

      - name: Lint scripts
        run: npm run eslint

      - name: Run tests
        run: npm run test
