name: CI | Unit

defaults:
  run:
    shell: bash

on:
  push:
    branches:
      - '**'

jobs:

  ci-unit:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install
        run: npm ci --ignore-scripts

      - name: Lint scripts
        run: npm run eslint

      - name: Run tests
        run: npm run test
