name: Release stable channel

defaults:
  run:
    shell: bash

on: [workflow_dispatch]

jobs:

  release-stable:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: '0'
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup git
        run: |
          git config user.name "kendo-bot"
          git config user.email "kendouiteam@progress.com"

      - name: Merge develop to master
        run: |
          git fetch --quiet
          git reset --hard origin/master
          git merge --ff-only --quiet origin/develop

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install
        run: npm ci

      - name: Publish
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Update develop
        run: |
          git push origin master:develop --quiet > /dev/null 2>&1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
